/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controlador.Controlador;

/**
 *
 * @author toba_2_6_7
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private final Controlador controlador;
    /**
     * Creates new form VentanaPrincipal
     * @param c
     */
    public VentanaPrincipal(Controlador c) {
        this.controlador = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlb_principal = new javax.swing.JToolBar();
        btn_reclamos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_configuraciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Reclamos");

        tlb_principal.setRollover(true);

        btn_reclamos.setText("Reclamos");
        btn_reclamos.setFocusable(false);
        btn_reclamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reclamos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlb_principal.add(btn_reclamos);

        jButton1.setText("Articulos");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tlb_principal.add(jButton1);

        jButton2.setText("Tecnicos");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlb_principal.add(jButton2);

        btn_configuraciones.setText("Config");
        btn_configuraciones.setFocusable(false);
        btn_configuraciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_configuraciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_configuraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionesActionPerformed(evt);
            }
        });
        tlb_principal.add(btn_configuraciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlb_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlb_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_configuracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionesActionPerformed
        VtnConfiguraciones vc = new VtnConfiguraciones(this.controlador, this);
        this.setVisible(false);
        vc.setLocationRelativeTo(null);
        vc.setResizable(false);
        vc.setVisible(true);
    }//GEN-LAST:event_btn_configuracionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VtnArticulos va = new VtnArticulos(this.controlador, this);
        this.setVisible(false);
        va.setLocationRelativeTo(null);
        va.setResizable(false);
        va.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configuraciones;
    private javax.swing.JButton btn_reclamos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToolBar tlb_principal;
    // End of variables declaration//GEN-END:variables
}
