/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import modelo.*;
import controlador.Controlador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author toba_2_6_7
 */
public class VtnArticulos extends javax.swing.JFrame {
    private final Controlador controlador;
    private final JFrame previo;

    /**
    * Creates new form VtnArticulos
    *
    * @param c
    * @param p
    */
    public VtnArticulos(Controlador c, JFrame p) {
        this.controlador = c;
        this.previo = p;
        initComponents();
        reiniciarArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstArticulos = new javax.swing.JList();
        btnGuardarArticulo = new javax.swing.JButton();
        btnEliminarArticulo = new javax.swing.JButton();
        btnNuevoArticulo = new javax.swing.JButton();
        txtNombreArticulo = new javax.swing.JTextField();
        cmbTipoArticulo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Articulos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lstArticulos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArticulosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstArticulos);

        btnGuardarArticulo.setText("Guardar");
        btnGuardarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArticuloActionPerformed(evt);
            }
        });

        btnEliminarArticulo.setText("Eliminar");
        btnEliminarArticulo.setEnabled(false);
        btnEliminarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArticuloActionPerformed(evt);
            }
        });

        btnNuevoArticulo.setText("Nuevo");
        btnNuevoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoArticuloActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tipo de Articulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevoArticulo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarArticulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarArticulo)
                    .addComponent(btnEliminarArticulo)
                    .addComponent(btnNuevoArticulo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArticuloActionPerformed
        if (this.cmbTipoArticulo.getSelectedItem() == null) {
            this.controlador.mensaje("MA", "Debe seleccionar un tipo de articulo obligatoriamente.\n\nEn caso de no contar con articulos cargados dirijase a:\n\n\tConfiguracion->Pestaña Tipo de Articulo\n\ny proceda con la carga del tipo que necesite", "Atención");
            return;
        }
        
        if (this.txtNombreArticulo.getText().isEmpty()) {
            this.controlador.mensaje("MA", "Debe establecer el nombre del Articulo obligatoriamente.", "Atención");
            return;
        }
        
        if (!this.lstArticulos.isSelectionEmpty()) {
            Articulo a = (Articulo) this.lstArticulos.getSelectedValue();
            String nNombre = this.txtNombreArticulo.getText();
            TipoDeArticulo tda = (TipoDeArticulo) this.cmbTipoArticulo.getSelectedItem();
            this.controlador.editarArticulo(a, nNombre, tda);
        } else {
            String nNombre = this.txtNombreArticulo.getText();
            TipoDeArticulo tda = (TipoDeArticulo) this.cmbTipoArticulo.getSelectedItem(); 
            this.controlador.agregarArticulo(nNombre, tda);
        }
        reiniciarArticulos();
    }//GEN-LAST:event_btnGuardarArticuloActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void lstArticulosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArticulosValueChanged
        // verificamos que la lista tenga un item seleccionado
        if (!this.lstArticulos.isSelectionEmpty()) {
            // Activo los el boton para permitir la eliminacion
            this.btnEliminarArticulo.setEnabled(true);
            // obtengo el item seleccionado
            Articulo a = (Articulo) this.lstArticulos.getSelectedValue();
            // asigno los valores de los atributos a las caja de texto
            this.txtNombreArticulo.setText(a.getNombre());
            if (a.getTipoDeArticulo()!= null) {
                this.cmbTipoArticulo.setSelectedItem(a.getTipoDeArticulo());
            } else {
                this.cmbTipoArticulo.setSelectedItem(null);
            }
        } else {
            // Desactivo el boton para permitir la eliminacion
            this.btnEliminarArticulo.setEnabled(false);
        }
    }//GEN-LAST:event_lstArticulosValueChanged

    private void btnEliminarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArticuloActionPerformed
        Articulo a = (Articulo) this.lstArticulos.getSelectedValue();
        if (a != null) {
            int transaccion = this.controlador.eliminarArticulo(a);
            if (transaccion != 0) {
                this.controlador.mensajeErrorPersistencia("EPE", "el ", "articulo", "Error de Persistencia");
            }
            reiniciarArticulos();
        }
    }//GEN-LAST:event_btnEliminarArticuloActionPerformed

    private void btnNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoArticuloActionPerformed
        reiniciarArticulos();
    }//GEN-LAST:event_btnNuevoArticuloActionPerformed

    private void reiniciarArticulos() {
        // Cargamos la lista
        this.lstArticulos.setListData(this.controlador.listarArticulos().toArray());
        // deselecciono la lista
        this.lstArticulos.clearSelection();
        this.txtNombreArticulo.setText("");
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(this.controlador.listarTiposDeArticulo().toArray());
        this.cmbTipoArticulo.setModel(modeloCombo);
        this.cmbTipoArticulo.setSelectedIndex(-1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarArticulo;
    private javax.swing.JButton btnGuardarArticulo;
    private javax.swing.JButton btnNuevoArticulo;
    private javax.swing.JComboBox<String> cmbTipoArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstArticulos;
    private javax.swing.JTextField txtNombreArticulo;
    // End of variables declaration//GEN-END:variables
}
