/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controlador.Controlador;
import modelo.*;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import java.text.SimpleDateFormat;

/**
 *
 * @author toba_2_6_7
 */
public class VtnReclamosPrincipal extends javax.swing.JFrame {

    private final Controlador controlador;
    private final JFrame previo;

    /**
     * Creates new form VtnProyectos
     *
     * @param c
     * @param p
     */
    public VtnReclamosPrincipal(Controlador c, JFrame p) {
        this.controlador = c;
        this.previo = p;
        initComponents();
        reiniciarReclamosPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReclamos = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        lblNumeroReclamo = new javax.swing.JLabel();
        lblFechaEntradaReclamo = new javax.swing.JLabel();
        SpnFecha = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        btnEditarDetalleReclamo = new javax.swing.JButton();
        btnNuevoReclamo = new javax.swing.JButton();
        btnGuardarReclamo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblFechaFinReclamo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbArticulo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reclamos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Número");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha de Entrada");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de Entrega");
        jLabel3.setToolTipText("Hace referencia a una fecha de entrega estimada.");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lstReclamos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstReclamosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstReclamos);

        jLabel4.setText("Descripción");

        SpnFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        SpnFecha.setToolTipText("Año");
        SpnFecha.setAutoscrolls(true);

        jScrollPane2.setViewportView(txtDescripcion);

        btnEditarDetalleReclamo.setText("Editar Detalles del Reclamo");
        btnEditarDetalleReclamo.setEnabled(false);
        btnEditarDetalleReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDetalleReclamoActionPerformed(evt);
            }
        });

        btnNuevoReclamo.setText("Nuevo");
        btnNuevoReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoReclamoActionPerformed(evt);
            }
        });

        btnGuardarReclamo.setText("Guardar");
        btnGuardarReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarReclamoActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Articulo");

        jCheckBox1.setText("Baja reclamo");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha de Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbArticulo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumeroReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblFechaEntradaReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNuevoReclamo)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarReclamo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addGap(196, 196, 196)
                                .addComponent(lblFechaFinReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SpnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarDetalleReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblNumeroReclamo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblFechaEntradaReclamo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SpnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblFechaFinReclamo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)))
                        .addGap(11, 11, 11)
                        .addComponent(cmbArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarDetalleReclamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoReclamo)
                            .addComponent(btnGuardarReclamo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarReclamoActionPerformed
            if (this.cmbArticulo.getSelectedItem() == null) {
                this.controlador.mensaje("MA", "Es OBLIGATORIO que defina el articulo para el cual esta Creando/Editando el Reclamo", "Advertencia");
                return;
            }
            if (!this.lstReclamos.isSelectionEmpty()) {
                Reclamo r = (Reclamo) this.lstReclamos.getSelectedValue();
                String nDescripcionProblema = this.txtDescripcion.getText();
                Articulo a = (Articulo) this.cmbArticulo.getSelectedItem();
                Date f = (Date) this.SpnFecha.getValue();
                this.controlador.editarReclamo(r, nDescripcionProblema, f, a);
            } else {
                String nDescripcionProblema = this.txtDescripcion.getText();
                Articulo a = (Articulo) this.cmbArticulo.getSelectedItem();
                Date f = (Date) this.SpnFecha.getValue();
                this.controlador.agregarReclamo(nDescripcionProblema, f, a);
            }
            reiniciarReclamosPrincipal();
    }//GEN-LAST:event_btnGuardarReclamoActionPerformed

    private void lstReclamosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstReclamosValueChanged
        Reclamo r = (Reclamo) this.lstReclamos.getSelectedValue();
        if (r != null) {
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            // Habilito los botones deshabilitados
            this.btnEditarDetalleReclamo.setEnabled(true);

            // Lleno las cajas de texto y demas
            this.txtDescripcion.setText(r.getDescProblema());
            this.SpnFecha.setValue(r.getFechaEstimEntrega());
            this.cmbArticulo.setSelectedItem(r.getArticulo());
            this.lblFechaEntradaReclamo.setText(f.format(r.getFechaEntrada()));
            this.lblNumeroReclamo.setText(String.valueOf(r.getNumero()));
        } else {
            // Desabilito los botones habilitados
            this.btnEditarDetalleReclamo.setEnabled(false);
        }
    }//GEN-LAST:event_lstReclamosValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnNuevoReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoReclamoActionPerformed
        reiniciarReclamosPrincipal();
    }//GEN-LAST:event_btnNuevoReclamoActionPerformed

    private void btnEditarDetalleReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDetalleReclamoActionPerformed
        Reclamo r = (Reclamo) this.lstReclamos.getSelectedValue();
        VtnReclamosDetalle vrd = new VtnReclamosDetalle(this.controlador, this, r);
        this.setVisible(false);
        vrd.setLocationRelativeTo(null);
        vrd.setResizable(false);
        vrd.setVisible(true);
    }//GEN-LAST:event_btnEditarDetalleReclamoActionPerformed

private void reiniciarReclamosPrincipal() {
    this.lstReclamos.setListData(this.controlador.listarReclamos().toArray());
    this.lblNumeroReclamo.setText("");
    this.lblFechaEntradaReclamo.setText("");
    this.lblFechaFinReclamo.setText("");
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(this.controlador.listarArticulos().toArray());
    this.cmbArticulo.setModel(modeloCombo);
    this.cmbArticulo.setSelectedIndex(-1);
    this.txtDescripcion.setText("");
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnFecha;
    private javax.swing.JButton btnEditarDetalleReclamo;
    private javax.swing.JButton btnGuardarReclamo;
    private javax.swing.JButton btnNuevoReclamo;
    private javax.swing.JComboBox<String> cmbArticulo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFechaEntradaReclamo;
    private javax.swing.JLabel lblFechaFinReclamo;
    private javax.swing.JLabel lblNumeroReclamo;
    private javax.swing.JList lstReclamos;
    private javax.swing.JTextPane txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
